version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: web
    volumes:
      - /app/node_modules
      - .:/app
    ports:
    - 3000:3000
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tests
    volumes:
     - /app/node_modules
     - .:/app
    command: ["npm", "run", "test"]